### ISSUE TITLE
您好，我测试了一下，有点问题

### ISSUE THREAD

**Issue by LiyongLuo** [XayahSuSuSu/XueTangxGetAnswer#1]
mJson = json.loads(response.text)
request.get回来的文本时请购买课程后再学习
但是我只有一个免费课程呀，这个必须付费课程才能用么

**Comment by LiyongLuo** [comment]
经过几次测试，感觉是api的连接有问题了

**Comment by XayahSuSuSu** [comment]
需要修改课程ID

**Comment by LiyongLuo** [comment]
嗯嗯，解决了，但是
eachChapter = section_leaf_list[m]
leaf_list = eachChapter['leaf_list']
在这里的时候，报错，eachChapter中没有leaf_list了

**Comment by XayahSuSuSu** [comment]
接口或者元素可能更新，也许你需要重新抓下包检查下了

**Comment by LiyongLuo** [comment]
我重新检查了一下了，发现api返回的json中‘is_show_answer : false’，已经没有answer这一项了，感觉答案已经不返回了，哎，可惜了
